AUGMENTATION: True
IMAGE_SIZE: [224,224,3] #as per VGG16 model, it s required to have the image size as 224,224,3
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 0
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.01
