artifacts_dir: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://chickenfecalimgs.s3.us-east-2.amazonaws.com/Chicken_fecal_imgs.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
