artifacts_dir: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://chickenfecalimgs.s3.us-east-2.amazonaws.com/Chicken_fecal_imgs.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.h5
  updated_base_model_path: artifacts/base_model/base_model_updated.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_root_log
  checkpoint_model_file_path: artifacts/prepare_callbacks/checkpoint_model/model.h5


model_train:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  
